### PR TITLE
Updated the template to inlclude pgsql_pg_hba

### PR DESCRIPTION
**Pull request by salindaliyanage**
Init.pp already has support for this paramater, but required configuration was missing in postgresql.yml.erb template.

Thanks.

### CODE REVIEW

**Comment by jadestorm** [comment]
Looks good!  Thank you, merging in!

**Comment by jadestorm** [comment]
@salindaliyanage Before I go to release a new version of the module -- is there anything else you were planning on adding/adjusting that you haven't submitted yet?

**Comment by salindaliyanage** [comment]
Thank you for merging in. Module was very useful. Please hold for one more day before release, I actually figured out an error in my previous commit (pgsql_custom_conf in the template should be custom_conf), that I will need to fix (sorry). Plus I am deploying the code to our staging environment today and I will see if anything else turned up.

**Comment by salindaliyanage** [comment]
Thank you for quick responses and actions.  I have submitted #5, and that should conclude my updates. Appreciate a new release to the module.

**Pull request merged**
